Imports System.ComponentModel

Public Class Nacionalidad
    <Browsable(False)>
    Public Property ID As Integer = 0
    Public Property Pais As String = String.Empty
    <Browsable(False)>
    Public Property Gentilicio As String = String.Empty

#Region "Funciones y Metodos"
    Public Sub New()
        MyBase.New
    End Sub
    Public Sub New(ByVal piID As Integer, ByVal psPais As String, ByVal psGentilicio As String)
        ID = piID
        Pais = psPais
        Gentilicio = psGentilicio
    End Sub

    Public Function CargarListado() As List(Of Nacionalidad)
        Dim Resultado As New List(Of Nacionalidad) From {
            New Nacionalidad(1, "Afganistán", "Afgana"),
            New Nacionalidad(2, "Albania", "Albansa"),
            New Nacionalidad(3, "Alemania", "Alemána"),
            New Nacionalidad(4, "Andorra", "Andorrana"),
            New Nacionalidad(5, "Angola", "Angoleña"),
            New Nacionalidad(6, "Antigua y Barbuda", "Antiguana"),
            New Nacionalidad(7, "Arabia Saudita", "Saudita"),
            New Nacionalidad(8, "Argelia", "Argelina"),
            New Nacionalidad(9, "Argentina", "Argentina"),
            New Nacionalidad(10, "Armenia", "Armenia"),
            New Nacionalidad(11, "Australia", "Australiana"),
            New Nacionalidad(12, "Austria", "Austríaca"),
            New Nacionalidad(13, "Azerbaiyán", "Azerbaiyana"),
            New Nacionalidad(14, "Bahamas", "Bahameña"),
            New Nacionalidad(15, "Bangladés", "Bangladesí"),
            New Nacionalidad(16, "Barbados", "Barbadense"),
            New Nacionalidad(17, "Baréin", "Bareiní"),
            New Nacionalidad(18, "Bélgica", "Belga"),
            New Nacionalidad(19, "Belice", "Beliceña"),
            New Nacionalidad(20, "Benín", "Beninesa"),
            New Nacionalidad(21, "Bielorrusia", "Bielorrusa"),
            New Nacionalidad(22, "Birmania / Myanmar", "Birmana"),
            New Nacionalidad(23, "Bolivia", "Boliviana"),
            New Nacionalidad(24, "Bosnia y Herzegovina", "Bosnia"),
            New Nacionalidad(25, "Botsuana", "Botsuana"),
            New Nacionalidad(26, "Brasil", "Brasileña"),
            New Nacionalidad(27, "Brunéi", "Bruneana"),
            New Nacionalidad(28, "Bulgaria", "Búlgara"),
            New Nacionalidad(29, "Burkina Faso", "Burkines"),
            New Nacionalidad(30, "Burundi", "Burundesa"),
            New Nacionalidad(31, "Bután", "Butanesa"),
            New Nacionalidad(32, "Cabo Verde", "Caboverdiana"),
            New Nacionalidad(33, "Camboya", "Camboyana"),
            New Nacionalidad(34, "Camerún", "Camerunesa"),
            New Nacionalidad(35, "Canadá", "Canadiense"),
            New Nacionalidad(36, "Catar", "Catarí"),
            New Nacionalidad(37, "Chad", "Chadiana"),
            New Nacionalidad(38, "Chile", "Chilena"),
            New Nacionalidad(39, "China", "China"),
            New Nacionalidad(40, "Chipre", "Chipriota"),
            New Nacionalidad(41, "Ciudad del Vaticano", "Vaticana"),
            New Nacionalidad(42, "Colombia", "Colombiana"),
            New Nacionalidad(43, "Comoras", "Comorense"),
            New Nacionalidad(44, "Corea del Norte", "Norcoreana"),
            New Nacionalidad(45, "Corea del Sur", "Surcoreana"),
            New Nacionalidad(46, "Costa de Marfil", "Marfileña"),
            New Nacionalidad(47, "Costa Rica", "Costarricense"),
            New Nacionalidad(48, "Croacia", "Croata"),
            New Nacionalidad(49, "Cuba", "Cubana"),
            New Nacionalidad(50, "Dinamarca", "Danesa"),
            New Nacionalidad(51, "Dominica", "Dominiques"),
            New Nacionalidad(52, "Ecuador", "Ecuatoriana"),
            New Nacionalidad(53, "Egipto", "Egipcia"),
            New Nacionalidad(54, "El Salvador", "Salvadoreña"),
            New Nacionalidad(55, "Emiratos Árabes Unidos", "Emiratí"),
            New Nacionalidad(56, "Eritrea", "Eritrea"),
            New Nacionalidad(57, "Eslovaquia", "Eslovaca"),
            New Nacionalidad(58, "Eslovenia", "Eslovena"),
            New Nacionalidad(59, "España", "Española"),
            New Nacionalidad(60, "Estados Unidos", "Estadounidense"),
            New Nacionalidad(61, "Estonia", "Estonia"),
            New Nacionalidad(62, "Etiopía", "Etíope"),
            New Nacionalidad(63, "Filipinas", "Filipina"),
            New Nacionalidad(64, "Finlandia", "Finlandesa"),
            New Nacionalidad(65, "Fiyi", "Fiyiana"),
            New Nacionalidad(66, "Francia", "Francesa"),
            New Nacionalidad(67, "Gabón", "Gabonesa"),
            New Nacionalidad(68, "Gambia", "Gambiana"),
            New Nacionalidad(69, "Georgia", "Georgiana"),
            New Nacionalidad(70, "Ghana", "Ghanesa"),
            New Nacionalidad(71, "Granada", "Granadina"),
            New Nacionalidad(72, "Grecia", "Griega"),
            New Nacionalidad(73, "Guatemala", "Guatemalteca"),
            New Nacionalidad(74, "Guyana", "Ecuatoguineana"),
            New Nacionalidad(75, "Guinea", "Guineana"),
            New Nacionalidad(76, "Guinea ecuatorial", "Guineana"),
            New Nacionalidad(77, "Guinea-Bisáu", "Guyanesa"),
            New Nacionalidad(78, "Haití", "Haitiana"),
            New Nacionalidad(79, "Honduras", "Hondureña"),
            New Nacionalidad(80, "Hungría", "Húngara"),
            New Nacionalidad(81, "India", "Hindú"),
            New Nacionalidad(82, "Indonesia", "Indonesia"),
            New Nacionalidad(83, "Irak", "Iraquí"),
            New Nacionalidad(84, "Irán", "Iraní"),
            New Nacionalidad(85, "Irlanda", "Irlandesa"),
            New Nacionalidad(86, "Islandia", "Islandesa"),
            New Nacionalidad(87, "Islas Marshall", "Marshalesa"),
            New Nacionalidad(88, "Islas Salomón", "Salomonense"),
            New Nacionalidad(89, "Israel", "Israelí"),
            New Nacionalidad(90, "Italia", "Italiana"),
            New Nacionalidad(91, "Jamaica", "Jamaiquina"),
            New Nacionalidad(92, "Japón", "Japonesa"),
            New Nacionalidad(93, "Jordania", "Jordana"),
            New Nacionalidad(94, "Kazajistán", "Kazaja"),
            New Nacionalidad(95, "Kenia", "Keniana"),
            New Nacionalidad(96, "Kirguistán", "Kirguisa"),
            New Nacionalidad(97, "Kiribati", "Kiribatiana"),
            New Nacionalidad(98, "Kuwait", "Kuwaití"),
            New Nacionalidad(99, "Laos", "Laosiana"),
            New Nacionalidad(100, "Lesoto", "Lesotense"),
            New Nacionalidad(101, "Letonia", "Letna"),
            New Nacionalidad(102, "Líbano", "Libanesa"),
            New Nacionalidad(103, "Liberia", "Liberiana"),
            New Nacionalidad(104, "Libia", "Libia"),
            New Nacionalidad(105, "Liechtenstein", "liechtensteiniana"),
            New Nacionalidad(106, "Lituania", "Lituana"),
            New Nacionalidad(107, "Luxemburgo", "Luxemburguesa"),
            New Nacionalidad(108, "Madagascar", "Malgache"),
            New Nacionalidad(109, "Malasia", "Malasia"),
            New Nacionalidad(110, "Malaui", "Malauí"),
            New Nacionalidad(111, "Maldivas", "Maldiva"),
            New Nacionalidad(112, "Malí", "Maliense"),
            New Nacionalidad(113, "Malta", "Maltesa"),
            New Nacionalidad(114, "Marruecos", "Marroquí"),
            New Nacionalidad(115, "Mauricio", "Mauriciana"),
            New Nacionalidad(116, "Mauritania", "Mauritana"),
            New Nacionalidad(117, "México", "Mexicana"),
            New Nacionalidad(118, "Micronesia", "Micronesia"),
            New Nacionalidad(119, "Moldavia", "Moldava"),
            New Nacionalidad(120, "Mónaco", "Monegasca"),
            New Nacionalidad(121, "Mongolia", "Mongla"),
            New Nacionalidad(122, "Montenegro", "Montenegrina"),
            New Nacionalidad(123, "Mozambique", "Mozambiqueña"),
            New Nacionalidad(124, "Namibia", "Namibia"),
            New Nacionalidad(125, "Nauru", "Nauruana"),
            New Nacionalidad(126, "Nepal", "Nepalí"),
            New Nacionalidad(127, "Nicaragua", "Nicaragüense"),
            New Nacionalidad(128, "Níger", "Nigerina"),
            New Nacionalidad(129, "Nigeria", "Nigeriana"),
            New Nacionalidad(130, "Noruega", "Noruega"),
            New Nacionalidad(131, "Nueva Zelanda", "Neozelandesa"),
            New Nacionalidad(132, "Omán", "Omaní"),
            New Nacionalidad(133, "Países Bajos", "Neerlandesa"),
            New Nacionalidad(134, "Pakistán", "Pakistaní"),
            New Nacionalidad(135, "Palaos", "Palauana"),
            New Nacionalidad(136, "Panamá", "Panameña"),
            New Nacionalidad(137, "Papúa Nueva Guinea", "Papú"),
            New Nacionalidad(138, "Paraguay", "Paraguaya"),
            New Nacionalidad(139, "Perú", "Peruana"),
            New Nacionalidad(140, "Polonia", "Polaca"),
            New Nacionalidad(141, "Portugal", "Portuguesa"),
            New Nacionalidad(142, "Reino Unido", "Británica"),
            New Nacionalidad(143, "República Centroafricana", "Centroafricana"),
            New Nacionalidad(144, "República Checa", "Checa"),
            New Nacionalidad(145, "República de Macedonia", "Macedonia"),
            New Nacionalidad(146, "República del Congo", "Congoleña"),
            New Nacionalidad(147, "República Democrática del Congo", "Congoleña"),
            New Nacionalidad(148, "República Dominicana", "Dominicana"),
            New Nacionalidad(149, "República Sudafricana", "Sudafricana"),
            New Nacionalidad(150, "Ruanda", "Ruandesa"),
            New Nacionalidad(151, "Rumanía", "Rumana"),
            New Nacionalidad(152, "Rusia", "Rusa"),
            New Nacionalidad(153, "Samoa", "Samoana"),
            New Nacionalidad(154, "San Cristóbal y Nieves", "Cristobaleña"),
            New Nacionalidad(155, "San Marino", "Sanmarinense"),
            New Nacionalidad(156, "San Vicente y las Granadinas", "Sanvicentina"),
            New Nacionalidad(157, "Santa Lucía", "Santalucense"),
            New Nacionalidad(158, "Santo Tomé y Príncipe", "Santotomense"),
            New Nacionalidad(159, "Senegal", "Senegalesa"),
            New Nacionalidad(160, "Serbia", "Serbia"),
            New Nacionalidad(161, "Seychelles", "Seychellense"),
            New Nacionalidad(162, "Sierra Leona", "Sierraleonesa"),
            New Nacionalidad(163, "Singapur", "Singapurense"),
            New Nacionalidad(164, "Siria", "Siria"),
            New Nacionalidad(165, "Somalia", "Somalí"),
            New Nacionalidad(166, "Sri Lanka", "Ceilanesa"),
            New Nacionalidad(167, "Suazilandia", "Suazi"),
            New Nacionalidad(168, "Sudán", "Sursudanesa"),
            New Nacionalidad(169, "Sudán del Sur", "Sudanesa"),
            New Nacionalidad(170, "Suecia", "Sueca"),
            New Nacionalidad(171, "Suiza", "Suiza"),
            New Nacionalidad(172, "Surinam", "Surinamesa"),
            New Nacionalidad(173, "Tailandia", "Tailandesa"),
            New Nacionalidad(174, "Tanzania", "Tanzana"),
            New Nacionalidad(175, "Tayikistán", "Tayika"),
            New Nacionalidad(176, "Timor Oriental", "Timorense"),
            New Nacionalidad(177, "Togo", "Togolesa"),
            New Nacionalidad(178, "Tonga", "Tongana"),
            New Nacionalidad(179, "Trinidad y Tobago", "Trinitense"),
            New Nacionalidad(180, "Túnez", "Tunecina"),
            New Nacionalidad(181, "Turkmenistán", "Turcomana"),
            New Nacionalidad(182, "Turquía", "Turca"),
            New Nacionalidad(183, "Tuvalu", "Tuvaluana"),
            New Nacionalidad(184, "Ucrania", "Ucraniana"),
            New Nacionalidad(185, "Uganda", "Ugandesa"),
            New Nacionalidad(186, "Uruguay", "Uruguaya"),
            New Nacionalidad(187, "Uzbekistán", "Uzbeka"),
            New Nacionalidad(188, "Vanuatu", "Vanuatuense"),
            New Nacionalidad(189, "Venezuela", "Venezolana"),
            New Nacionalidad(190, "Vietnam", "Vietnamita"),
            New Nacionalidad(191, "Yemen", "Yemení"),
            New Nacionalidad(192, "Yibuti", "Yibutiana"),
            New Nacionalidad(193, "Zambia", "Zambiana"),
            New Nacionalidad(194, "Zimbabue", "Zimbabuense")
        }
        Return Resultado
    End Function

    Public Function Buscar(psGentilicio As String) As Nacionalidad
        Dim Resultado As New Nacionalidad
        Resultado = Nacionalidades.Find(Function(x) x.Gentilicio = psGentilicio)
        Return Resultado
    End Function
#End Region
End Class
